name: "Initialize Geode"
description: "A GitHub Action to initialize the Geode environment"
author: "Your Name"
icon: "activity"
color: "gray-dark"
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Geode
      run: |
        # Update and install dependencies
        sudo apt update
        sudo apt upgrade
        sudo apt install git cmake ninja-build python3 python3-pip

        # Clone the Geode SDK repository
        git clone https://github.com/geode-sdk/geode.git
        cd geode


        # Build the Geode SDK
        mkdir build
        cd build
        cmake -G "Ninja" -DGEODE_TARGET_PLATFORM=windows ..
        ninja

        # Install the Geode CLI
        sudo cp geode /usr/local/bin/

        # Verify the installation
        geode --version

      shell: bash
