name: "Initialize Geode"
description: "A GitHub Action to initialize the Geode environment"
author: "Your Name"
icon: activity
color: purple
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Geode
      run: |
        git clone https://github.com/geode-sdk/cli.git
        git clone https://github.com/geode-sdk/sdk.git
        cd cli
        cmake ..
        make
      shell: bash
